// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import { defineConfig, env } from 'prisma/config';

dotenv.config({ path: `.env` });

export function buildDatabaseUrl(): string {
  const username = env('DB_USERNAME');
  const password = env('DB_PASSWORD');
  const host = env('DB_HOST');
  const port = env('DB_PORT');
  const database = env('DB_NAME');

  return `postgresql://${username}:${password}@${host}:${port}/${database}?schema=public`;
}

export default defineConfig({
  schema: 'prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: buildDatabaseUrl(),
  },
});
